# Config file for automatic testing at travis-ci.org

language: python
dist: buster

python:
  - "3.8"

env: 
  - TOX_ENV=py38-django-30

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg
  - pip install poetry

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: poetry install -v

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
